Merged in feature/CLinting (pull request #37)
Feature/CLinting

* no message

* adjusted python script to normalize the path

* added quotes around path arg so slashes are not dropped on execution

* replacing "\n" with os.linesep

* updated type in report from string to text for the endpoint

* omitting empty link line

* trying to omit type:text to see if plain text works instead of json string

* printing the request for debugging purposes

* incorrect brackets on print call fixed

* removing ticket number incase the null value is causing issues

* trying \n again instead of linesep as it seems the json spec doesn't like the \r

* isolating parts of the request to try and find problem section

* no message

* I think report type was incorrect from api docs "Valid values: PASSED, FAILED, PENDING"

* removed exit since we now want the pipeline to run no matter what.

* re-added throwing of error, it will catch and fail the stage but continue running the other stages.

* Merge branch 'main' of bitbucket.org:VARLab/devops-pipeline into feature/CLinting

* no message

* theres a problem with the pipeline, using a .dll to convert the unity test xml report to html, which is severely outdated, it seems the code coverage report can generate the report in html itself instead of running this .dll which is causing issues with the updated .net sdk

* trying to force the .net to roll forward for the unity dll

* removing html conversion of test results for now.

* removed roll forward since it didn't work

* re adding no graphics option

* Updated deployment file

* clean up from PR


Approved-by: Chris Park
Approved-by: Jonathan Bezeau

diff --git a/JenkinsfileDeployment b/JenkinsfileDeployment
--- a/JenkinsfileDeployment
+++ b/JenkinsfileDeployment
@@ -87,6 +87,48 @@ pipeline {
                     echo "Identifying Unity version..."
                     env.UNITY_EXECUTABLE = util.getUnityExecutable(WORKSPACE, PROJECT_DIR)
                 }
+
+                // Initial running the project on Unity Editor    
+                echo "Running Unity in batch mode to setup initial files..."
+                dir ("${PROJECT_DIR}") {
+                    script {
+                        sh "git checkout ${PR_BRANCH}"
+                        def logFile = "${PROJECT_DIR}/batch_mode_execution.log"
+
+                        def flags = "-batchmode -nographics -projectPath \"${PROJECT_DIR}\" -executeMethod \"Packages.Rider.Editor.RiderScriptEditor.SyncSolution\" -logFile \"${logFile}\" -quit "
+                        
+                        echo "Flags set to: ${flags}"
+                        
+                        // Execute Unity in batch mode with memory settings
+                        def exitCode = sh(script: """\"${env.UNITY_EXECUTABLE}\" ${flags}""", returnStatus: true)
+                        
+                        // Handle exit code
+                        if (exitCode != 0) {
+                            sh "exit ${exitCode}"
+                        }
+                    }
+                }
+            }
+        }
+        //linting stage to check formatting
+        stage('Linting')
+        {
+            steps{
+                //Linting
+                echo "running lint script"
+                script {
+                    echo "Parameters for bash: ${WORKSPACE}/Linting.bash ${PROJECT_DIR} ${REPORT_DIR}"
+                    def exitCode = sh script: "sh \'${WORKSPACE}/Bash/Linting.bash\' \'${PROJECT_DIR}\' \'${REPORT_DIR}\'", returnStatus: true 
+                    echo "After bash call, exit code: ${exitCode}"
+                    //handle exit code here no reports to be sent, since this for deployment and not PRs
+                    if(exitCode != 0)
+                    {
+                        //in this case we set build result to failure since we don't want to deploy bad code
+                        catchError(buildResult: 'FAILURE', stageResult: 'FAILURE'){
+                            error("Linting failed with exit code: ${exitCode}") //we exit no matter what on error code != 0
+                        }
+                    }
+                }
             }
         }
         // Runs the project's EditMode tests. Unlike the PR pipeline, if any tests fail, this will cause the pipeline to fail.
